@BASE_URL = http://localhost:3000/api

GET {{BASE_URL}}


###
GET {{BASE_URL}}/users

###
GET {{BASE_URL}}/users/99

###

GET http://localhost:3000/

###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name": "gökhan1 özdemir",
    "email": "ozdemirgok16@gmal.co",
    "userName": "godaqd",
    "password": "12345"
}

###
POST http://localhost:3000/
Content-Type: application/json

{
    "isim" : "gökhan",
    "yas" : "28"
}

###
POST http://localhost:3000/
Content-Type: application/x-www-form-urlencoded

username=gokhan&yas=32

###
PATCH {{BASE_URL}}/users/6065b7da19a18c26dc193e0d
Content-Type: application/json

{
    "email": "sdsd@sdsd.cv"
}

###
DELETE {{BASE_URL}}/users/6067085b824d592c4c11109

